# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  buildPath: '/build'


pool:
  name: 'Local'
  vmImage: ubuntu-latest

# Install Node JS
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js 16'

# Install npm dependencies of the project
- script: |
    npm install
  displayName: 'npm install'

# Built the react project
- script: |
    npm run build
  displayName: 'npm run build'

# Zip the content of the built folder
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Publish the zip file as an artifact to later be deployed 
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'


# Deploy the application to webAPP services, which is a windows web app
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'GNG-5300-Service-Account'
    appType: 'webApp'
    WebAppName: 'gng-5300-react-app'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'